.travis.yml, Makefile
=> Add version target and fix travis.yml

pkg/data/generic.go, pkg/opa/opa.go, pkg/opa/opa_test.go, pkg/types/types.go
- Use correct method for removing objects
- Recover from errors by resetting data for object type
- Refactor path building
=> Fix issues in generic sync

README.md, docs/admission-control-secure.md
Signed-off-by: Ashutosh Narkar <anarkar4387@gmail.com>
=> Add docs for deploying OPA securely as an admission controller.

cmd/kube-mgmt/main.go
The flag `--enable-policies` is enabled by default but can be disabled with `--enable-policies=false`.
Signed-off-by: Alban Crequy <alban@kinvolk.io>
=> policies: add option to enable/disable sync

README.md, docs/admission-control-crd.md
Fixes #24
Signed-off-by: Ashutosh Narkar <anarkar4387@gmail.com>
=> Add tutorial for Admission Control For Custom Resources

cmd/kube-mgmt/main.go, docs/admission-control-secure.md
This PR adds support for reading the opa auth token from
a file so it isn't leaked out in a process list.
=> Support --opa-auth-token-file

Makefile
=> Prepare v0.9 development

README.md
=> Add note to README about wildcard

cmd/kube-mgmt/main.go, pkg/data/generic.go
There is a death spiral in this code if resyncPeriod is too low: if
the number of objects in the API server is too many for OPA to accept
within this time interval, kube-mgmt will endlessly spin on trying to
PUT them all. Hence, this setting must be adjusted to be high enough
for any deployment, and has no safe default other than 0.
I'm leaving the default at 60s for this change, to preserve existing
behaviour.
=> Move resyncPeriod into the --replicate-resync flag

README.md
=> Remove no need line

Dockerfile
make this image run rootless
Closes #57
=> make image run rootless

README.md
=> fix some grammar bugs

.github/workflows/opa-helm-chart-release.yaml
As requested I have simplified and reduced in scope the event filtering for the helm chart release workflow.
=> Simplify event filtering for helm chart release

cmd/kube-mgmt/main.go
This adds two new flags, `--opa-ca-file` and `--opa-allow-insecure`, in order to enable use cases where OPA uses a certificate signed by an internal certificate authority.
The implementation simple overrides the default TLS configuration, so the rest of the code can continue to rely on the default HTTP client.
Fixes #82
=> Add options to set CA certificate or use insecure TLS

README.md
srenatus on your community slack asked me to hand in this PR
=> Feedback on documentation readme json-loading

charts/opa/templates/deployment.yaml, charts/opa/values.yaml
* move configuration from values to template
* port can be changed more easily
Signed-off-by: Ievgenii Shepeliuk <eshepelyuk@gmail.com>
=> fix: simplify checks

charts/opa/templates/deployment.yaml, charts/opa/values.yaml
=> fix: watch release namespace by default

cmd/kube-mgmt/main.go
Fixes https://github.com/open-policy-agent/kube-mgmt/issues/136
=> Ignore unknown flags

charts/opa/values.yaml
Signed-off-by: Ievgenii Shepeliuk <eshepelyuk@gmail.com>
=> fix: opa 0.40.0

charts/opa-kube-mgmt/templates/poddisruptionbudget.yaml
=> helm: use PodDisruptionBudget policy/v1 when policy/v1beta1 is removed

charts/opa-kube-mgmt/values.yaml
=> helm: update default openpolicyagent/opa image to 0.47.3

skaffold.yaml
Should help address https://github.com/open-policy-agent/kube-mgmt/issues/191
=> Alpine 3.16.4

README.md
annotation was renamed in PR163, see also https://github.com/open-policy-agent/kube-mgmt/pull/163
=> fix doc bug

README.md
Correct the smallest of typos in the README
=> Fix an example annotation value in the README

README.md
I've found a very minor typo in the README.md
fixed few typos.
=> Typo Fix in README.md

charts/opa-kube-mgmt/values.yaml
=> Update OPA image version to 0.69.0
