examples/service_validation/README.md, examples/service_validation/admission_controller.yaml, examples/service_validation/install.sh
This example has detailed instructions for verifying that Kubernetes service
objects do not accidentally expose a loadBalancer to the world.
It uses OPA to create the required policy and enforcing it.
=> Example for validating Kubernetes Service objects.

cmd/kube-mgmt/main.go, pkg/policies/configmap.go
Previously kube-mgmt would load policies out configmaps matching
namespace or label. This made it difficult to restrict kube-mgmt to a
subset of configmaps in a specific namespace.
Fixes #14
=> Add configmap matching on namespace AND label

cmd/kube-mgmt/main.go, pkg/opa/opa.go, pkg/opa/opa_test.go
This allows for an authentication token to be used to call opa server.
Usage:
--opa-auth-token=$(OPA_BEARER_TOKEN)
Signed-off-by: Kevin Downey <kevin_downey@intuit.com>
=> Add opa-auth-token to args.

docs/admission-control-crd.md
This avoids the need to update the image every time we cut a release.
=> Remove kube-mgmt image from CRD example

manifests/deployment.yml
This is a trivial change fixing a typo, however considering this file is embedded in https://www.openpolicyagent.org/docs/kubernetes-admission-control.html (see `3. Deploy OPA on top of Kubernetes`) and therefore has a greater level of visibility for people taking this tutorial, I thought it was a typo worth fixing.
=> Fix a typo in manifests/deployment.yml

pkg/data/generic.go
@tsandall 
This PR fixes a panic when the generic resource watcher receives a Delete event of type DeletedFinalStateUnknown as documented [here](https://github.com/kubernetes/client-go/blob/843f7c4f28b1f647f664f883697107d5c02c5acc/1.5/tools/cache/controller.go#L146-L149)
=> Fix panic onDelete for DeletedFinalStateUnknown

pkg/policies/configmap.go
@tsandall 
This PR adds the feature that allows kube-mgmt to be configured to search for config maps with the required label in all namespaces without having to specify all the namespaces.
=> Added support to replicate configmaps in multiple namespaces with "*"

cmd/kube-mgmt/main.go, pkg/configmap/configmap.go
this fixes an inconsistency with the docs:
> --policies stringSlice
>                            automatically load policies from these namespaces 
but `v1.NamespaceAll` was hardcoded
=> allow multiple namespaces to be watched for policies

pkg/data/generic.go, pkg/data/generic_test.go
When sync'ing resources kube-mgmt would do a delete and then a PUT
request for each object. This will aggregate all of the objects into
one PUT request.
=> Change resource sync to use PATCH instead of PUTs

pkg/configmap/configmap.go
After running for some time (e.g., 30 minutes to an hour) kube-mgmt
would begin logging the following errors:
E0904 12:18:45.089926 1 streamwatcher.go:109] Unable to decode an event from the watch stream: unable to decode watch event: no kind "Status" is registered for version "v1" in scheme "github.com/open-policy-agent/kube-mgmt/pkg/configmap/configmap.go:102"
This error seems to be referring to the Status field indirectly found
on the ConfigMap type (via the Initializers field.) After running this
version of kube-mgmt overnight, the error no longer occurs and the
configmaps are still be synchronized.
=> Fix decode error message on configmap synchronizer

docs/admission-control-secure.md
When following this guide, [after using the initial ingress tutorial](https://www.openpolicyagent.org/docs/latest/kubernetes-tutorial/) I hit a bug where the pod would crash loop. 
Once I enabled `debug` logging I saw the following messages:
```json 
{
"client_addr": "10.244.0.1:52444",
"level": "info",
"msg": "Sent response.",
"req_id": 1,
"req_method": "GET",
"req_path": "/health",
"resp_body": "{\n  \"code\": \"unauthorized\",\n  \"message\": \"request rejected by administrative policy\"\n}\n",
"resp_bytes": 87,
"resp_duration": 2.773603,
"resp_status": 401,
"time": "2020-01-20T12:33:33Z"
}
```
As the tutorial YAML I started from had the readiness and liveness probes configured the auth policy in this guide was causing the pod to be restarted as requests to `/health` failed. 
This PR …
=> Add allow /health for readiness probe

pkg/configmap/configmap.go
This PR checks the previous version of the updated ConfigMap and if it used to match the label `openpolicyagent.org` (policy or data): removes the corresponding policies from OPA.
Here is a small test I did on my local minishift cluster (Kubernetes: v1.11.0+d4cacc0, OpenShift: v3.11.0+0cbc58b):
```
oc get pod opa-5-7v6pd --template='{{range .spec.containers}}{{if eq .name "kube-mgmt"}}{{.image}}{{"\n"}}{{end}}{{end}}'
openpolicyagent/kube-mgmt:0.12-dev2
oc create configmap mandatory-labels-pod --from-file=./policies/labels/mandatory/pod/mandatory-labels.rego
configmap/mandatory-labels-pod created
minishift ssh
[docker@minishift ~]$ curl -s -o /dev/null -k -w "%{http_code}" https://172.30.121.201/v1/policies/my-opa/mandatory-labels-pod/mandatory-labels.rego && echo
404
oc label cm …
```
=> Remove the policy from OPA if ConfigMap's label was removed

pkg/configmap/configmap.go
When kube-mgmt was started with the "--policies=*" option, it would set the array of namespaces with an emtpy string as its only element. This would break the logic of how namespaces are matched thereby not annotating configmaps containing policy and hence policies would not be loaded.
Fixes: #55
Signed-off-by: Ashutosh Narkar <anarkar4387@gmail.com>
=> Fix logic to load policies from all namespaces

README.md
The documentation mentions using `--policies` for loading in policy
ConfigMaps and then explains using some other flags and annotations
for loading JSON data. It doesn't explicitly say that the data
ConfigMap needs to also be in the list of namespaces for `--policies`,
which is somewhat confusing just due to the naming (in theory there
may not be _any_ policies involved, just data).
This just adds a note into the README to be a little more explicit.
Signed-off-by: Patrick East <east.patrick@gmail.com>
=> README: Add note about using `--policies` for data

manifests/deployment.yml
- update deployment apiVersion to apps/v1 (available since 1.9, today we're in 1.18)
- add missing label selector
=> fix deployment manifest

.github/workflows/opa-helm-chart-release.yaml, build/helm-gh-pages.sh, charts/opa/Chart.yaml, charts/opa/OWNERS, charts/opa/README.md, charts/opa/templates/NOTES.txt, charts/opa/templates/_helpers.tpl, charts/opa/templates/deployment.yaml, charts/opa/templates/mgmt-clusterrole.yaml, charts/opa/templates/mgmt-clusterrolebinding.yaml, charts/opa/templates/poddisruptionbudget.yaml, charts/opa/templates/sar-clusterrole.yaml, charts/opa/templates/sar-clusterrolebinding.yaml, charts/opa/templates/secrets.yaml, charts/opa/templates/service.yaml, charts/opa/templates/serviceaccount.yaml, charts/opa/templates/servicemonitor.yaml, charts/opa/templates/webhookconfiguration.yaml, charts/opa/values.yaml
Hello OPA team!
As you know, the official helm chart repository is now deprecated, and vendors have to find a place where to publish and distribute their helm charts. 
This is the reason why we post here: https://github.com/helm/charts/pull/8915#issuecomment-728050130 to help your team hosting the OPA helm chart in another location. Thanks to @tsandall, he created a team granting access to this repository.
```bash
$ helm repo add open-policy-agent https://open-policy-agent.github.io/kube-mgmt/charts
$ helm repo update
Hang tight while we grab the latest from your chart repositories...
...Successfully got an update from the "open-policy-agent" chart repository
Update Complete. ⎈Happy Helming!⎈
$ helm search repo opa
NAME                    CHART VERSION   APP VERSION     DESCRIPTION …
```
=> OPA Helm chart migration

charts/opa/templates/webhookconfiguration.yaml
Small fix for the issue in k8s 1.19+
> x509: certificate relies on legacy Common Name field, use SANs or temporarily enable Common Name matching with GODEBUG=x509ignoreCN=0
Issue related to new Go version: https://v1-19.docs.kubernetes.io/docs/setup/release/notes/
> The deprecated, legacy behavior of treating the CommonName field on X.509 serving certificates as a host name when no Subject Alternative Names are present is now disabled by default. It can be temporarily re-enabled by adding the value x509ignoreCN=0 to the GODEBUG environment variable. (#93264, @justaugustus) [SIG API Machinery, Auth, CLI, Cloud Provider, Cluster Lifecycle, Instrumentation, Network, Node, Release, Scalability, Storage and Testing]
Before:
After:
=> Provide a list of alternate DNS names for the genSignedCert function

charts/opa/README.md
We were still using the `stable` hosted chart in the README, replaced with the correct one defined few lines above (`open-policy-agent`).
=> Using the correct repo in README's helm command

Makefile, charts/opa/values.yaml, examples/service_validation/admission_controller.yaml, manifests/deployment.yml
AFAICT there is no automation for release notes, right?
I had to rollback the `VERSION` variable in the `Makefile` because it's used to build the image from the github action.
If this is fine I can merge it, tag it and add the description manually. Let me know. :shipit:
=> Preparing v0.12.1 release

cmd/kube-mgmt/flag_test.go, cmd/kube-mgmt/main.go, pkg/configmap/configmap.go
--policy-label=my.org/policy
--policy-value=mutating
I would like two run separate OPA servers using the same policy namespace. Currently openpolicyagent.org/policy=rego" is hard coded.
=> allow custom label openpolicyagent.org/policy=rego

charts/opa/Chart.yaml, charts/opa/templates/mgmt-clusterrolebinding.yaml
Currently `helm lint` fails with the error
```
helm lint .
==> Linting .
[ERROR] templates/mgmt-clusterrolebinding.yaml: the kind "rbac.authorization.k8s.io/v1beta1 ClusterRoleBinding" is deprecated in favor of "rbac.authorization.k8s.io/v1 ClusterRoleBinding"
Error: 1 chart(s) linted, 1 chart(s) failed
```
Hence updating the CRB apiVersion to `rbac.authorization.k8s.io/v1`
=> Update ClusterRoleBinding apiVersion

charts/opa/README.md, charts/opa/templates/deployment.yaml, charts/opa/values.yaml
This would allow users to specify environment variables that would be added to the OPA container, so that they could be picked up in Rego scripts ex. for making API calls using authentication.
=> Add environment variables to OPA container

charts/opa/README.md, charts/opa/templates/webhookconfiguration.yaml, charts/opa/values.yaml
Hardcoded certificate duration when using cert-manager may be insufficient in some cases (compare to using `generateCerts`, which creates certificate with 10 year validity).
In this proposal, the duration of the certificates generated by cert-manager is made configurable. The previously hardcoded values are retained as default values (5y for CA and 1y for serving certificate).
=> Make cert-manager certs duration configurable

charts/opa/README.md, charts/opa/templates/webhookconfiguration.yaml, charts/opa/values.yaml
Enable setting annotations on admissioncontroller resources. This, for instance, allows for ArgoCD PreSync hooks to be used to guarantee the correct syncing order.
=> Enable setting admissioncontroller annotations

charts/opa/templates/webhookconfiguration.yaml
The Webhook Configuration should support both "v1beta1" as well as "v1" of AdmissionReviews.
https://kubernetes.io/docs/reference/access-authn-authz/extensible-admission-controllers/#configure-admission-webhooks-on-the-fly
Otherwise the following error occurs (on a v1.21 cluster):
> Internal error occurred: failed calling webhook "webhook.openpolicyagent.org": converting (v1.AdmissionReview) to (v1beta1.AdmissionReview): unknown conversion
=> Add support for v1 admissionReviewVersions

pkg/configmap/configmap.go
This PR addresses two issues with how ConfigMap annotations are handled:
- #90
- #131
=> Fixes issues with ConfigMap annotations

charts/opa/README.md, charts/opa/templates/_helpers.tpl, charts/opa/templates/deployment.yaml
Fixes https://github.com/open-policy-agent/kube-mgmt/issues/130
=> [helm] Make dns policy configurable

charts/opa-kube-mgmt/templates/rbac-mgmt.yaml, charts/opa-kube-mgmt/values.yaml
- This PR undoes parts of [fix: simplify rbac creation #108](https://github.com/open-policy-agent/kube-mgmt/pull/108)
- This is required if a user is using replication as the pod may need access to other resources depending on the policies being enforced
=> make rbac rules configurable for replication

charts/opa-kube-mgmt/templates/deployment.yaml
Hello,
thanks for keeping up the good work in this repo!
I wanted to upgrade to the latest 7.0.0 release, but came across this minor issue in Helm output:
```
Error: YAML parse error on opa-kube-mgmt/templates/deployment.yaml:
error converting YAML to JSON: yaml: line 45: did not find expected '-' indicator
```
This is due to minor indentation misalignment - yay YAML!
=> Fix indentation of OPA extraArgs in deployment.yaml

skaffold.yaml
Update the base image to 3.12.12 to fix the following CVE's:
- CVE-2021-28831
- CVE-2021-30139
- CVE-2021-36159
- CVE-2021-42375
- CVE-2021-423{78-86}
- CVE-2018-25032
- CVE-2022-28391
Fixes #164
=> Fix vulnerabilities found in the Alpine Base image

.gitignore, docs/admission-control-secure.md
There were few recent changes that might be considered breaking changes like https://github.com/open-policy-agent/kube-mgmt/pull/151 or https://github.com/open-policy-agent/kube-mgmt/pull/163 where for example `--polices` was renamed into `--namespace` or statusAnnotationKey value from `openpolicyagent.org/policy-status` to `openpolicyagent.org/kube-mgmt-status`
This PR updates the docs so that they reflect the latest changes.
Signed-off-by: Adrian Aneci <aneci.adrian@gmail.com>
=> Update docs after latest changes

charts/opa-kube-mgmt/templates/deployment.yaml
resolve https://github.com/open-policy-agent/kube-mgmt/issues/168
Actually with the chart release (7.0.6) when you try to set some specific resource limits to the kube-mgmt deployment like for exemple.
mgmt:
limits:
cpu: 0.5
memory: 128Mi
requests:
cpu: 0.1
memory: 64Mi
The release will fail because of the render of the deployment.yaml
For fix it we need to give the correct indent to the added ressource.
Signed-off-by: Remy Genisson <genisson.remy@gmail.com>
=> correct indent

skaffold.yaml
The 3.12.x line is out of support. Move to the latest version to get back on a supported version. This also addresses CVE-2022-37434.
=> Update the base image to Alpine to 3.16.2

.github/workflows/release.yaml
https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
=> workflow: update set-output usage

charts/opa-kube-mgmt/templates/deployment.yaml, charts/opa-kube-mgmt/templates/mgmt-token-secret.yaml, charts/opa-kube-mgmt/values.yaml, test/e2e/custom_mgmt_token/test.sh, test/e2e/custom_mgmt_token/values.yaml, test/linter/test.sh
This PR adds an optional functionality to mount and use existing secret as mgmt-token for the helm chart, instead of generating a new one. This is useful when specifying more than 1 replica and we want them to use the same token.
=> Implemented optional use of existing secret for mgmt token

charts/opa-kube-mgmt/templates/deployment.yaml, charts/opa-kube-mgmt/values.yaml, test/linter/test.sh
Currently we have ability to specify `extraVolumes` values.yaml:  https://github.com/open-policy-agent/kube-mgmt/blob/master/charts/opa-kube-mgmt/values.yaml#L268, however it is not possible to mount and use them in the OPA pod. This PR adds the volumeMounts that can be used to mount them.
=> Added extraVolumeMounts for mounting extraVolumes into OPA pod

charts/opa-kube-mgmt/templates/poddisruptionbudget.yaml
Previously the chart used the deprecated apiVersion policy/v1beta1 as long as it was avaiable in the cluster. This is against the recommendation of upgrading the release to a supported apiVersion prior to upgrading the cluster to a version that removes the deprecated apiVersion: <https://helm.sh/docs/topics/kubernetes_apis/#helm-users>
Closes #184
=> helm chart: fix the upgrade of the PodDisruptionBudget's apiVersion

cmd/kube-mgmt/main.go, pkg/data/generic.go, pkg/data/generic_test.go, test/e2e/fixture-replication.yaml, test/e2e/replication/test.sh, test/e2e/replication/values.yaml, test/e2e/replication_ignore_namespaces/test.sh, test/e2e/replication_ignore_namespaces/values.yaml
We have a need to ignore namespaces.  This PR adds a way to do this with `--replicate-ignore-namespaces`, in another PR i would like to attempt to add `--replicate-ignore-annotations`, so that `control-plane.alpha.kubernetes.io/leader` could be added for those who choose to.  For this PR however the scope is limited just to ignore-namespaces as its easier to implement and users with a similar problem can leverage it to solve any immediate issues. 
What happens is when you load configmaps for whatever reason all the leader elections update every X seconds and then kube-mgmt then bombards OPA with reloads. This has the effect of driving load thru the roof, see screenshot below. This is a 5 second trace and the heap is going crazy!!!
Here is an example of a configmap with a leader election …
=> add a way to ignore namespaces

pkg/data/generic.go, pkg/data/generic_test.go
fixes https://github.com/open-policy-agent/kube-mgmt/issues/195
prior to this patch, when a kube-mgmt is configured to replicate cluster scoped resources client-go fails with:
```
W0328 20:56:18.838009       1 reflector.go:324]
k8s.io/client-go@v0.23.8/tools/cache/reflector.go:167: failed to list
*unstructured.Unstructured: field label not supported:
metadata.namespace
E0328 20:56:18.838180       1 reflector.go:138]
k8s.io/client-go@v0.23.8/tools/cache/reflector.go:167: Failed to watch
*unstructured.Unstructured: failed to list *unstructured.Unstructured:
field label not supported: metadata.namespace
```
similar reproducer with `kubectl` is as below:
```
kubectl get ns --field-selector metadata.namespace!=foo
Error from server (BadRequest): Unable to find "/v1,
Resource=namespaces" that …
```
=> skip setting ignore namespace fieldSelector on cluster scoped resources.

charts/opa-kube-mgmt/templates/servicemonitor.yaml
Current `ServiceMonitor` template defines `http` as destination port for scraping metrics data, which is not set in the `Service` manifest.
This commit updates the `ServiceMonitor` manifest to use `diag` port, which is exposed when prometheus is enabled.
=> fix: helm chart serviceMonitor port definition

charts/opa-kube-mgmt/templates/deployment.yaml, charts/opa-kube-mgmt/values.yaml, test/e2e/labels/values.yaml, test/e2e/multi/values.yaml, test/e2e/no_https/values.yaml
Fixes #210
Fix provided:
Before starting kube-mgmt container, the startup probe will check the health of OPA container using the API `<HTTP-SCHEME>://127.0.0.1:<OPA-PORT>/health` 
kubectl describe pod:
```
Startup:        http-get https://:8181/health delay=20s timeout=1s period=10s #success=1 #failure=5
```
Pod came up successfully with the change
```
kc get pods
NAME                                 READY   STATUS    RESTARTS   AGE
opa-opa-kube-mgmt-66ff988f55-5wdjv   2/2     Running   0          32s
```
=> Adding startup probe for kube-mgmt container

skaffold.yaml
Fixes #191 
This PR updates the Alpine base image to 3.16.6, which is the latest version of Alpine 3.16. The image resolves the the two high vulnerabilities reported in the previous image.
=> Update the base image to Alpine to 3.16.6

skaffold.yaml
Pulling in fixes for some OS CVEs
[CVE-2023-2975](https://security.alpinelinux.org/vuln/CVE-2023-2975)
[CVE-2023-3446](https://security.alpinelinux.org/vuln/CVE-2023-3446)
[CVE-2023-3817](https://security.alpinelinux.org/vuln/CVE-2023-3817)
=> Update the base image Alpine to 3.16.7

charts/opa-kube-mgmt/templates/serviceaccount.yaml, charts/opa-kube-mgmt/values.schema.json, charts/opa-kube-mgmt/values.yaml, test/lint/sa.yaml, test/unit/sa_test.yaml
ServiceAccount annotations are needed to support web identity credentials: https://www.openpolicyagent.org/docs/latest/management-bundles/#web-identity-credentials
=> Add template for ServiceAccount annotations

skaffold.yaml
Upgrade of base alpine image to latest.
Ran trivy scan on base image and no vulnerabilities encouuntered.
Before fix:
After upgrade of alpine image:
Closes #247
=> Update alpine image to 3.19.1 to fix CVE for base image- CVE-2023-5678

skaffold.yaml
Update base alpine image to 3.20.2 to get fixes for CVEs.
Signed-off-by: porwalameet <porwalameet@gmail.com>
=> Update  base alpine image to 3.20.2

charts/opa-kube-mgmt/templates/deployment.yaml
Changing the webhook sometimes results into the creation of a new certificate and because of that an updated secret.
The updated secret introduces the following error:
`tls: failed to verify certificate: x509: certificate signed by unknown authority (possibly because of "crypto/rsa: verification error" while trying to verify candidate authority certificate "opa-admission-ca")`
The secret is updated in the pod (since kubernetes automatically updates mounted secrets and configmaps), but the OPA process does not reload the secrets. After restarting the pods the issue is solved, we now how to do this manually for each update to this chart.
Adding the sha256 of the certificate secret as an annotation will result in an update to the deployment and thus restarting its pods.
=> Add webhookconfig checksum to deployment annotations

charts/opa-kube-mgmt/templates/service.yaml, charts/opa-kube-mgmt/values.schema.json, charts/opa-kube-mgmt/values.yaml, test/e2e/custom_config/values.yaml, test/lint/service.yaml, test/unit/service.yaml
- adding helm chart functionality to specify Service annotations and `trafficDistribution` configuration to allow users to configure shortest path to the pods
=> feat: add Service annotations
